USE ROLE SYSADMIN;

--CREATION OF WAREHOUSE
CREATE OR REPLACE WAREHOUSE KIPITHON_WH;

--CREATION OF DB AND SCHEMA
CREATE OR REPLACE DATABASE KIPITHON_DB;

USE role SYSADMIN;
CREATE OR REPLACE SCHEMA "KIPITHON_DB"."LANDING";
CREATE OR REPLACE SCHEMA "KIPITHON_DB"."TRANSFORM";
CREATE OR REPLACE SCHEMA "KIPITHON_DB"."REPORTING";
CREATE OR REPLACE SCHEMA "KIPITHON_DB"."GIT_SCHEMA";





