USE DATABASE KIPITHON_DB;
CREATE SCHEMA GIT_SCHEMA;
USE SCHEMA GIT_SCHEMA;

USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE SECRET KIPITHON_GITHUB_SECRET
TYPE=PASSWORD
USERNAME='KIPITHON_GIT'
PASSWORD='Kipithon@123';

SHOW SECRETS;

DESC SECRET KIPITHON_GITHUB_SECRET;

--CREATING GIT API INTEGRATION
CREATE OR REPLACE API INTEGRATION KIPITHON_GIT_API_INTEGRATION
API_PROVIDER=GIT_HTTPS_API
API_ALLOWED_PREFIXES=('https://github.com/sahilkipi/')
ALLOWED_AUTHENTICATION_SECRETS=(KIPITHON_GITHUB_SECRET)
ENABLED=TRUE;

SHOW INTEGRATIONS;

SHOW API INTEGRATIONS;

DESC API INTEGRATION KIPITHON_GIT_API_INTEGRATION;

--CREATING GIT REPOSITORY
CREATE OR REPLACE GIT REPOSITORY KIPITHON_GIT_REPO
API_INTEGRATION=KIPITHON_GIT_API_INTEGRATION
GIT_CREDENTIALS=KIPITHON_GITHUB_SECRET
ORIGIN='https://github.com/sahilkipi/kipithon.git';

SHOW GIT REPOSITORIES;

DESC GIT REPOSITORY KIPITHON_GIT_REPO;

--WORKING WITH GIT REPOSITORY

LIST @KIPITHON_GIT_REPO/branches/dev_snowflake;

SHOW GIT BRANCHES IN KIPITHON_GIT_REPO;








