USE ROLE SECURITYADMIN;

--CREATION OF KIPITHON ADMIN ROLE WHO HAS ACCOUNT ADMIN PPRIVILEGES
CREATE OR REPLACE ROLE KIPITHON_ADMIN; --ADMIN ROLE

USE ROLE USERADMIN;
CREATE or replace USER KIPITHON_ADM PASSWORD='Kipiadm@1234' DEFAULT_ROLE = KIPITHON_ADMIN MUST_CHANGE_PASSWORD = false;

USE ROLE SECURITYADMIN;
GRANT ROLE KIPITHON_ADMIN TO ROLE ACCOUNTADMIN;

GRANT ROLE KIPITHON_ADMIN TO USER KIPITHON_ADM;

---------------------------------------------------------------------------------------------------------------------------------------------------------------
--CREATION OF DIFFERENT ROLES WITH RESPECT TO TASKS

CREATE OR REPLACE ROLE INGESTION_ROLE; -- GCP INGESTION TO SNF
CREATE OR REPLACE ROLE TRANSFORM_ROLE; -- SNF TRANSFORMATION if any
CREATE OR REPLACE ROLE REPORTING_ROLE; -- STREAMLIT
---------------------------------------------------------------------------------------------------------------------------------------------------------------
--GRANT USAGE ON DATABASE AND WAREHOUSE FOR INGESTION_ROLE
GRANT USAGE ON WAREHOUSE KIPITHON_WH TO ROLE INGESTION_ROLE;
GRANT USAGE ON DATABASE KIPITHON_DB TO ROLE INGESTION_ROLE; 
GRANT USAGE ON SCHEMA KIPITHON_DB.LANDING TO ROLE INGESTION_ROLE;

--GRANT USAGE AND PRIVILEGES ON THE DB OBJECTS TO ROLE INGESTION_ROLE
GRANT ROLE SYSADMIN TO ROLE INGESTION_ROLE;
GRANT ALL ON DATABASE KIPITHON_DB TO ROLE INGESTION_ROLE;
GRANT ALL ON SCHEMA  KIPITHON_DB.LANDING TO ROLE INGESTION_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA KIPITHON_DB.LANDING TO ROLE INGESTION_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA KIPITHON_DB.LANDING TO ROLE INGESTION_ROLE;
GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE ON ALL TABLES IN SCHEMA KIPITHON_DB.LANDING TO ROLE INGESTION_ROLE;
GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE ON ALL VIEWS IN SCHEMA KIPITHON_DB.LANDING TO ROLE INGESTION_ROLE;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA KIPITHON_DB.LANDING TO ROLE INGESTION_ROLE;
GRANT ALL ON ALL PROCEDURES IN SCHEMA KIPITHON_DB.LANDING TO ROLE INGESTION_ROLE;
GRANT USAGE ON ALL STAGES IN SCHEMA KIPITHON_DB.LANDING TO ROLE INGESTION_ROLE;
GRANT CREATE TABLE ON SCHEMA KIPITHON_DB.LANDING TO ROLE INGESTION_ROLE;
GRANT CREATE TASK ON SCHEMA KIPITHON_DB.LANDING TO ROLE INGESTION_ROLE; 
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE INGESTION_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE INGESTION_ROLE; 
GRANT CREATE FILE FORMAT ON SCHEMA KIPITHON_DB.LANDING TO ROLE INGESTION_ROLE;
GRANT SELECT,INSERT,UPDATE,DELETE ON  FUTURE TABLES IN SCHEMA KIPITHON_DB.LANDING TO ROLE INGESTION_ROLE;
GRANT SELECT,INSERT,UPDATE,DELETE ON  FUTURE VIEWS IN SCHEMA KIPITHON_DB.LANDING TO ROLE INGESTION_ROLE;
GRANT USAGE ON FUTURE STAGES IN SCHEMA KIPITHON_DB.LANDING TO ROLE INGESTION_ROLE;
--GRANT USAGE TO FILE FORMAT TO INGESTION ROLE
GRANT USAGE ON FILE FORMAT my_csv_format TO ROLE INGESTION_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA KIPITHON_DB.LANDING TO ROLE INGESTION_ROLE;


GRANT USAGE ON INTEGRATION my_integration TO ROLE INGESTION_ROLE;


GRANT INSERT ON TABLE KIPITHON_DB.LANDING.DB_HOST_SUMMARY_STG TO ROLE INGESTION_ROLE;

GRANT SELECT ON  FUTURE TABLES IN SCHEMA KIPITHON_DB.LANDING TO ROLE INGESTION_ROLE;
GRANT SELECT ON  FUTURE VIEWS IN SCHEMA KIPITHON_DB.LANDING TO ROLE INGESTION_ROLE;
GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE ON  FUTURE TABLES IN SCHEMA KIPITHON_DB.LANDING TO ROLE INGESTION_ROLE;
GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE ON  FUTURE VIEWS IN SCHEMA KIPITHON_DB.LANDING TO ROLE INGESTION_ROLE;
---------------------------------------------------------------------------------------------------------------------------------------------------------------
--GRANT USAGE ON DATABASE AND WAREHOUSE FOR TRANSFORM_ROLE
GRANT USAGE ON DATABASE KIPITHON_DB TO ROLE TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA KIPITHON_DB.TRANSFORM TO ROLE TRANSFORM_ROLE;
GRANT USAGE ON WAREHOUSE KIPITHON_WH TO ROLE TRANSFORM_ROLE;

--GRANT USAGE AND PRIVILEGES ON THE DB OBJECTS TO ROLE TRANSFORM_ROLE
GRANT ROLE SYSADMIN TO ROLE TRANSFORM_ROLE;
GRANT ALL ON DATABASE KIPITHON_DB TO ROLE TRANSFORM_ROLE;
GRANT ALL ON SCHEMA  KIPITHON_DB.TRANSFORM TO ROLE TRANSFORM_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA KIPITHON_DB.TRANSFORM TO ROLE INGESTION_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA KIPITHON_DB.TRANSFORM TO ROLE TRANSFORM_ROLE;
GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE ON ALL TABLES IN SCHEMA KIPITHON_DB.TRANSFORM TO ROLE TRANSFORM_ROLE;
GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE ON ALL VIEWS IN SCHEMA KIPITHON_DB.TRANSFORM TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA KIPITHON_DB.LANDING to ROLE TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA KIPITHON_DB.LANDING TO ROLE TRANSFORM_ROLE;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA KIPITHON_DB.TRANSFORM TO ROLE TRANSFORM_ROLE;
GRANT ALL ON ALL PROCEDURES IN SCHEMA KIPITHON_DB.TRANSFORM TO ROLE TRANSFORM_ROLE;
GRANT USAGE ON ALL STAGES IN SCHEMA KIPITHON_DB.TRANSFORM TO ROLE TRANSFORM_ROLE;
GRANT CREATE TABLE ON SCHEMA KIPITHON_DB.TRANSFORM TO ROLE TRANSFORM_ROLE;
GRANT CREATE TASK ON SCHEMA KIPITHON_DB.TRANSFORM TO ROLE TRANSFORM_ROLE; 
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE TRANSFORM_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE TRANSFORM_ROLE; 

GRANT SELECT ON TABLE KIPITHON_DB.LANDING.QUERY_HISTORY_RESULTS_STG TO ROLE TRANSFORM_ROLE;
GRANT OPERATE ON TASK KIPITHON_DB.LANDING.QUERY_HISTORY_INGEST TO ROLE TRANSFORM_ROLE;

GRANT SELECT ON  FUTURE TABLES IN SCHEMA KIPITHON_DB.LANDING TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON  FUTURE VIEWS IN SCHEMA KIPITHON_DB.LANDING TO ROLE TRANSFORM_ROLE;
GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE ON  FUTURE TABLES IN SCHEMA KIPITHON_DB.TRANSFORM TO ROLE TRANSFORM_ROLE;
GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE ON  FUTURE VIEWS IN SCHEMA KIPITHON_DB.TRANSFORM TO ROLE TRANSFORM_ROLE;
---------------------------------------------------------------------------------------------------------------------------------------------------------------

--GRANT USAGE ON DATABASE AND WAREHOUSE FOR REPORTING_ROLE
GRANT USAGE ON DATABASE KIPITHON_DB TO ROLE REPORTING_ROLE; 
GRANT USAGE ON SCHEMA KIPITHON_DB.REPORTING TO ROLE REPORTING_ROLE;
GRANT USAGE ON WAREHOUSE KIPITHON_WH TO ROLE REPORTING_ROLE;

--GRANT USAGE AND PRIVILEGES ON THE DB OBJECTS TO ROLE REPORTING ROLE
GRANT ALL ON DATABASE KIPITHON_DB TO ROLE REPORTING_ROLE;
GRANT ALL ON SCHEMA  KIPITHON_DB.REPORTING TO ROLE REPORTING_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA KIPITHON_DB.REPORTING TO ROLE REPORTING_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA KIPITHON_DB.REPORTING TO ROLE REPORTING_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA KIPITHON_DB.TRANSFORM to ROLE REPORTING_ROLE;
GRANT USAGE ON SCHEMA KIPITHON_DB.TRANSFORM TO ROLE REPORTING_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA KIPITHON_DB.LANDING to ROLE REPORTING_ROLE;
GRANT USAGE ON SCHEMA KIPITHON_DB.LANDING TO ROLE REPORTING_ROLE;
GRANT CREATE TABLE ON SCHEMA KIPITHON_DB.REPORTING TO ROLE REPORTING_ROLE;
GRANT CREATE VIEW ON SCHEMA KIPITHON_DB.REPORTING TO ROLE REPORTING_ROLE;

GRANT SELECT ON  FUTURE TABLES IN SCHEMA KIPITHON_DB.LANDING TO ROLE REPORTING_ROLE;
GRANT SELECT ON  FUTURE VIEWS IN SCHEMA KIPITHON_DB.LANDING TO ROLE REPORTING_ROLE;
GRANT SELECT ON  FUTURE TABLES IN SCHEMA KIPITHON_DB.TRANSFORM TO ROLE REPORTING_ROLE;
GRANT SELECT ON  FUTURE VIEWS IN SCHEMA KIPITHON_DB.TRANSFORM TO ROLE REPORTING_ROLE;
GRANT SELECT ON  FUTURE TABLES IN SCHEMA KIPITHON_DB.REPORTING TO ROLE REPORTING_ROLE;
GRANT SELECT ON  FUTURE VIEWS IN SCHEMA KIPITHON_DB.REPORTING TO ROLE REPORTING_ROLE;

---------------------------------------------------------------------------------------------------------------------------------------------------------------
--GRANT SUB ROLES TO MAIN ADMIN KIPITHON_ADMIN
GRANT ROLE INGESTION_ROLE TO ROLE KIPITHON_ADMIN;
GRANT ROLE TRANSFORM_ROLE TO ROLE KIPITHON_ADMIN;
GRANT ROLE REPORTING_ROLE TO ROLE KIPITHON_ADMIN;

--GRANT USAGE ON WAREHOUSE TO KIPITHON_ADMIN
GRANT USAGE ON WAREHOUSE KIPITHON_WH TO ROLE KIPITHON_ADMIN;
GRANT USAGE ON SCHEMA KIPITHON_DB.GIT_SCHEMA TO ROLE KIPITHON_ADMIN;

GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE KIPITHON_ADMIN;
GRANT USAGE ON INTEGRATION my_integration TO ROLE KIPITHON_ADMIN;

GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE SYSADMIN;
GRANT USAGE ON INTEGRATION my_integration TO ROLE SYSADMIN;

SHOW GRANTS TO ROLE KIPITHON_ADMIN;
        --GRANT ALL ON WAREHOUSE KIPITHON_WH TO ROLE KIPITHON_ADMIN;
---------------------------------------------------------------------------------------------------------------------------------------------------------------

--CREATION OF USERS AND ASSIGNING ROLES
USE ROLE USERADMIN;
CREATE OR REPLACE USER INGESTION_USR PASSWORD='ingestion123' DEFAULT_ROLE = INGESTION_ROLE MUST_CHANGE_PASSWORD = false;
CREATE OR REPLACE USER TRANSFORM_USR PASSWORD='transform123' DEFAULT_ROLE = TRANSFORM_ROLE MUST_CHANGE_PASSWORD = false;
CREATE OR REPLACE USER REPORTING_USR PASSWORD='reporting123' DEFAULT_ROLE = REPORTING_ROLE MUST_CHANGE_PASSWORD = false;

---------------------------------------------------------------------------------------------------------------------------------------------------------------
USE ROLE SECURITYADMIN;
GRANT ROLE INGESTION_ROLE TO USER INGESTION_USR;
GRANT ROLE TRANSFORM_ROLE TO USER TRANSFORM_USR;
GRANT ROLE REPORTING_ROLE TO USER REPORTING_USR;

---------------------------------------------------------------------------------------------------------------------------------------------------------------
SHOW WAREHOUSES;
SHOW ROLES;
SHOW USERS;

SHOW GRANTS ON TABLE KIPITHON_DB.LANDING.DB_HOST_SUMMARY_STG;






