SELECT * FROM KIPITHON_DB.LANDING.QUERY_HISTORY_RESULTS_STG WHERE DATE(INGEST_TMST)='2024-08-02';

SELECT * FROM KIPITHON_DB.LANDING.DB_OBJECT_OVERVIEW_STG;

SELECT * FROM KIPITHON_DB.LANDING.DB_HOST_SUMMARY_STG;

SELECT * FROM KIPITHON_DB.LANDING.SCHEMA_MEMORY_DETAILS_STG;

SELECT * FROM KIPITHON_DB.LANDING.VIEW_TBL_DEPENDENCY_STG;

list @GCP_STAGE;
show tasks;

---DB_OBJECT_OVERVIEW
USE schema LANDING;

---Runs at 8pm IST daily
CREATE or replace TASK OBJ_OVERVIEW_TRUNCATE
WAREHOUSE = 'KIPITHON_WH'
SCHEDULE = 'USING CRON 30 14 * * * UTC'
  AS
    TRUNCATE TABLE KIPITHON_DB.LANDING.DB_OBJECT_OVERVIEW_STG;

ALTER TASK OBJ_OVERVIEW_TRUNCATE SUSPEND;


CREATE or replace TASK OBJ_OVERVIEW_INGEST
AFTER OBJ_OVERVIEW_TRUNCATE
  AS
    copy into KIPITHON_DB.LANDING.DB_OBJECT_OVERVIEW_STG
    from @GCP_STAGE/DB_OBJECT_OVERVIEW/2024_08_02.csv
    file_format= KIPITHON_DB.LANDING.MY_CSV_FORMAT;

ALTER TASK OBJ_OVERVIEW_INGEST SUSPEND;


---SCHEMA_MEMORY_DETAILS_STG
USE schema LANDING;

---Runs at 8pm IST daily
CREATE or replace TASK SCHEMA_MEMORY_DETAILS_TRUNCATE
WAREHOUSE = 'KIPITHON_WH'
SCHEDULE = 'USING CRON 30 14 * * * UTC'
  AS
    TRUNCATE TABLE KIPITHON_DB.LANDING.SCHEMA_MEMORY_DETAILS_STG;

ALTER TASK SCHEMA_MEMORY_DETAILS_TRUNCATE SUSPEND;


CREATE or replace TASK SCHEMA_MEMORY_DETAILS_INGEST
AFTER SCHEMA_MEMORY_DETAILS_TRUNCATE
  AS
    copy into KIPITHON_DB.LANDING.SCHEMA_MEMORY_DETAILS_STG
    from @GCP_STAGE/Schema_memory_datails/2024_08_02.csv
    file_format= KIPITHON_DB.LANDING.MY_CSV_FORMAT;

ALTER TASK SCHEMA_MEMORY_DETAILS_INGEST SUSPEND;


---schema_performance_stats
USE schema LANDING;

---Runs at 8pm IST daily
CREATE or replace TASK DB_HOST_SUMMARY_TRUNCATE
WAREHOUSE = 'KIPITHON_WH'
SCHEDULE = 'USING CRON 30 14 * * * UTC'
  AS
    TRUNCATE TABLE KIPITHON_DB.LANDING.DB_HOST_SUMMARY_STG;

ALTER TASK DB_HOST_SUMMARY_TRUNCATE SUSPEND;


CREATE or replace TASK DB_HOST_SUMMARY_INGEST
AFTER DB_HOST_SUMMARY_TRUNCATE
  AS
    copy into KIPITHON_DB.LANDING.DB_HOST_SUMMARY_STG
    from @GCP_STAGE/Schema_performance_stats/2024_08_02.csv
    file_format= KIPITHON_DB.LANDING.MY_CSV_FORMAT;

ALTER TASK DB_HOST_SUMMARY_INGEST SUSPEND;


---query_history_details
USE schema LANDING;

---Runs at 8pm IST daily
CREATE or replace TASK QUERY_HISTORY_INGEST
WAREHOUSE = 'KIPITHON_WH'
SCHEDULE = 'USING CRON 30 14 * * * UTC'
  AS
    copy into KIPITHON_DB.LANDING.QUERY_HISTORY_RESULTS_STG
    from @GCP_STAGE/Query_History_Backup/2024_08_02.csv
    file_format= KIPITHON_DB.LANDING.MY_CSV_FORMAT;

ALTER TASK QUERY_HISTORY_INGEST SUSPEND;


CREATE or replace TASK QUERY_HISTORY_TBL_EXTRACTED
AFTER KIPITHON_DB.LANDING.QUERY_HISTORY_INGEST
  AS 
  INSERT INTO KIPITHON_DB.LANDING.QUERY_HISTORY_RESULTS_EXTRACT
  SELECT QUERY,DB_NAME,
  SPLIT_PART (
    SNOWFLAKE.CORTEX.COMPLETE (
      'mistral-large',
      CONCAT (
        'Extract the table names: <QUERY_HISTORY_RESULTS>',
        REPLACE(QUERY,'`','"'),
        '</QUERY_HISTORY_RESULTS>'
      )
    ),
    '"',
    2
  ) AS TABLE_NAME,
  FULL_SCAN,EXEC_COUNT,ERR_COUNT,TOTAL_LATENCY,max_latency,avg_latency, max_total_memory, rows_sent, rows_examined,rows_affected, first_seen, last_seen,INGEST_TMST
  FROM KIPITHON_DB.LANDING.QUERY_HISTORY_RESULTS_STG
  WHERE TO_DATE(INGEST_TMST) = CURRENT_DATE()-1;
  
ALTER TASK QUERY_HISTORY_TBL_EXTRACTED SUSPEND;



SELECT * FROM QUERY_HISTORY_RESULTS_EXTRACT;

---Runs at 8pm IST daily
CREATE or replace TASK VIEW_TBL_DEPENDENCY_TRUNCATE
WAREHOUSE = 'KIPITHON_WH'
SCHEDULE = 'USING CRON 30 14 * * * UTC'
  AS
    TRUNCATE TABLE KIPITHON_DB.LANDING.VIEW_TBL_DEPENDENCY_STG;

ALTER TASK VIEW_TBL_DEPENDENCY_TRUNCATE SUSPEND;


CREATE or replace TASK VIEW_TBL_DEPENDENCY_INGEST
AFTER VIEW_TBL_DEPENDENCY_TRUNCATE
  AS
    copy into KIPITHON_DB.LANDING.VIEW_TBL_DEPENDENCY_STG
    from @GCP_STAGE/Views_dependencies_info/
    file_format= KIPITHON_DB.LANDING.MY_CSV_FORMAT;

ALTER TASK VIEW_TBL_DEPENDENCY_INGEST SUSPEND;

SELECT * FROM KIPITHON_DB.LANDING.VIEW_TBL_DEPENDENCY_STG;

